# Generated by Django 5.2.8 on 2025-12-01 08:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroAcopio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('encargado', models.CharField(blank=True, max_length=100, null=True)),
                ('horario', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('horario_atencion', models.CharField(default='No especificado', max_length=255)),
                ('capacidad_toneladas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_donante', models.CharField(default='Persona', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('direccion_donante', models.CharField(blank=True, max_length=255, null=True)),
                ('ruc_dni', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('es_anonimo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialReciclable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_material', models.CharField(default='No especificado', max_length=50)),
                ('precio_por_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unidad_medida', models.CharField(default='kg', max_length=20)),
                ('es_toxico', models.BooleanField(default=False)),
                ('punto_acopio_recomendado', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_identificacion', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoReciclaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('puesto', models.CharField(blank=True, max_length=100, null=True)),
                ('turno', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(default='', max_length=255)),
                ('dni', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('fecha_contratacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('cargo', models.CharField(default='Operario', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('certificaciones', models.TextField(blank=True, null=True)),
                ('centro_acopio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_reciclaje.centroacopio')),
            ],
        ),
        migrations.CreateModel(
            name='RecepcionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('fecha_recepcion', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado_material', models.CharField(default='Recibido', max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('centro_acopio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reciclaje.centroacopio')),
                ('donante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_reciclaje.donante')),
                ('empleado_recepcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_reciclaje.empleadoreciclaje')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reciclaje.materialreciclable')),
            ],
        ),
        migrations.CreateModel(
            name='ProcesamientoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_proceso', models.CharField(max_length=100)),
                ('fecha_proceso', models.DateField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reciclaje.empleadoreciclaje')),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reciclaje.recepcionmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='VentaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_vendida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('centro_acopio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reciclaje.centroacopio')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reciclaje.materialreciclable')),
            ],
        ),
    ]
