# Generated by Django 5.2.8 on 2025-12-01 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroAcopio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_centro', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('horario_atencion', models.TextField()),
                ('capacidad_toneladas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Donante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_donante', models.CharField(max_length=255)),
                ('tipo_donante', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('direccion_donante', models.CharField(max_length=255)),
                ('ruc_dni', models.CharField(max_length=20)),
                ('fecha_registro', models.DateField()),
                ('es_anonimo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialReciclable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_material', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_material', models.CharField(max_length=50)),
                ('precio_por_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('es_toxico', models.BooleanField(default=False)),
                ('punto_acopio_recomendado', models.CharField(max_length=100)),
                ('codigo_identificacion', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoReciclaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empleado', models.CharField(max_length=255)),
                ('puesto', models.CharField(max_length=100)),
                ('fecha_contratacion', models.DateField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('centro_acopio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reciclaje.centroacopio')),
            ],
        ),
        migrations.CreateModel(
            name='RecepcionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_recepcion', models.DateField()),
                ('hora_recepcion', models.TimeField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('centro_acopio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reciclaje.centroacopio')),
                ('donante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_reciclaje.donante')),
                ('material_reciclable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reciclaje.materialreciclable')),
            ],
        ),
        migrations.CreateModel(
            name='ProcesamientoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_procesamiento', models.DateField()),
                ('tipo_procesamiento', models.CharField(max_length=100)),
                ('cantidad_procesada_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_resultante_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_procesamiento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reciclaje.empleadoreciclaje')),
                ('recepcion_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reciclaje.recepcionmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='VentaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField()),
                ('comprador', models.CharField(max_length=255)),
                ('cantidad_vendida_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True)),
                ('procesamiento_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reciclaje.procesamientomaterial')),
            ],
        ),
    ]
