# Generated by Django 5.0.13 on 2025-12-01 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reciclaje', '0002_rename_email_centroacopio_encargado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleadoreciclaje',
            name='turno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recepcionmaterial',
            name='empleado_recepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_reciclaje.empleadoreciclaje'),
        ),
        migrations.AlterField(
            model_name='donante',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donante',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donante',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empleadoreciclaje',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleadoreciclaje',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
