# Generated by Django 5.0.13 on 2025-12-01 08:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reciclaje', '0003_empleadoreciclaje_turno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centroacopio',
            name='capacidad_toneladas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='centroacopio',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='centroacopio',
            name='horario_atencion',
            field=models.CharField(default='No especificado', max_length=255),
        ),
        migrations.AddField(
            model_name='centroacopio',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='centroacopio',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='donante',
            name='direccion_donante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donante',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donante',
            name='es_anonimo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donante',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='donante',
            name='ruc_dni',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='donante',
            name='tipo_donante',
            field=models.CharField(default='Persona', max_length=50),
        ),
        migrations.AddField(
            model_name='empleadoreciclaje',
            name='apellido',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='empleadoreciclaje',
            name='cargo',
            field=models.CharField(default='Operario', max_length=100),
        ),
        migrations.AddField(
            model_name='empleadoreciclaje',
            name='certificaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleadoreciclaje',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='empleadoreciclaje',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleadoreciclaje',
            name='fecha_contratacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='materialreciclable',
            name='codigo_identificacion',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='materialreciclable',
            name='es_toxico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materialreciclable',
            name='precio_por_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='materialreciclable',
            name='punto_acopio_recomendado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='materialreciclable',
            name='tipo_material',
            field=models.CharField(default='No especificado', max_length=50),
        ),
        migrations.AddField(
            model_name='materialreciclable',
            name='unidad_medida',
            field=models.CharField(default='kg', max_length=20),
        ),
        migrations.AddField(
            model_name='recepcionmaterial',
            name='estado_material',
            field=models.CharField(default='Recibido', max_length=100),
        ),
        migrations.AddField(
            model_name='recepcionmaterial',
            name='fecha_recepcion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recepcionmaterial',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centroacopio',
            name='encargado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='centroacopio',
            name='horario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='centroacopio',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empleadoreciclaje',
            name='centro_acopio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_reciclaje.centroacopio'),
        ),
        migrations.AlterField(
            model_name='empleadoreciclaje',
            name='puesto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recepcionmaterial',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
